
/*

I could either have 50 constraints that stops
any values other than R, D, or T - Which Represents
Republicn, Democrat, or Third Party ... But That's
Rediculous..

*/
DROP TABLE States_T;

CREATE TABLE States_T
	(StateTableID			INT(8)					NOT NULL AUTO_INCREMENT,
	Alabama					VARCHAR(3),
    Alaska					VARCHAR(3),
    Arizona					VARCHAR(3),
    Arkansas				VARCHAR(3),
    California				VARCHAR(3),
    Colorado				VARCHAR(3),
    Connecticut				VARCHAR(3),
    Delaware				VARCHAR(3),
    Florida					VARCHAR(3),
    Georgia					VARCHAR(3),
    Hawaii					VARCHAR(3),
    Idaho					VARCHAR(3),
    Illinois				VARCHAR(3),
    Indiana					VARCHAR(3),
    Iowa					VARCHAR(3),
    Kansas					VARCHAR(3),
    Kentucky				VARCHAR(3),
    Louisiana				VARCHAR(3),
    Maine					VARCHAR(3),
    Maryland				VARCHAR(3),
    Massachusetts			VARCHAR(3),
    Michigan				VARCHAR(3),
    Minnesota				VARCHAR(3),
    Mississippi				VARCHAR(3),
    Missouri				VARCHAR(3),
    Montana					VARCHAR(3),
    Nebraska				VARCHAR(3),
    Nevada					VARCHAR(3),
    New_Hampshire			VARCHAR(3),
    New_Jersey				VARCHAR(3),
    New_Mexico				VARCHAR(3),
    New_York				VARCHAR(3),
    North_Carolina			VARCHAR(3),
    North_Dakota			VARCHAR(3),
    Ohio					VARCHAR(3),
    Oklahoma				VARCHAR(3),
    Oregon					VARCHAR(3),
    Pennsylvania			VARCHAR(3),
    Rhode_Island			VARCHAR(3),
    South_Carolina			VARCHAR(3),
    South_Dakota			VARCHAR(3),
    Tennessee				VARCHAR(3),
    Texas					VARCHAR(3),
    Utah					VARCHAR(3),
    Vermont					VARCHAR(3),
    Virginia				VARCHAR(3),
    Washington				VARCHAR(3),
    West_Virginia			VARCHAR(3),
    Wisconsin				VARCHAR(3),
    Wyoming					VARCHAR(3),
CONSTRAINT chk_Alabama CHECK (Alabama IN ('R', 'D', 'T')),
CONSTRAINT chk_Alaska CHECK (Alaska IN ('R', 'D', 'T')),
CONSTRAINT chk_Arizona CHECK (Arizona IN ('R', 'D', 'T')),
CONSTRAINT chk_Arkansas CHECK (Arkansas IN ('R', 'D', 'T')),
CONSTRAINT chk_California CHECK (California IN ('R', 'D', 'T')),
CONSTRAINT chk_Colorado CHECK (Colorado IN ('R', 'D', 'T')),
CONSTRAINT chk_Connecticut CHECK (Connecticut IN ('R', 'D', 'T')),
CONSTRAINT chk_Delaware CHECK (Delaware IN ('R', 'D', 'T')),
CONSTRAINT chk_Florida CHECK (Florida IN ('R', 'D', 'T')),
CONSTRAINT chk_Georgia CHECK (Georgia IN ('R', 'D', 'T')),
CONSTRAINT chk_Hawaii CHECK (Hawaii IN ('R', 'D', 'T')),
CONSTRAINT chk_Idaho CHECK (Idaho IN ('R', 'D', 'T')),
CONSTRAINT chk_Illinois CHECK (Illinois IN ('R', 'D', 'T')),
CONSTRAINT chk_Indiana CHECK (Indiana IN ('R', 'D', 'T')),
CONSTRAINT chk_Iowa CHECK (Iowa IN ('R', 'D', 'T')),
CONSTRAINT chk_Kansas CHECK (Kansas IN ('R', 'D', 'T')),
CONSTRAINT chk_Kentucky CHECK (Kentucky IN ('R', 'D', 'T')),
CONSTRAINT chk_Louisiana CHECK (Louisiana IN ('R', 'D', 'T')),
CONSTRAINT chk_Maine CHECK (Maine IN ('R', 'D', 'T')),
CONSTRAINT chk_Maryland CHECK (Maryland IN ('R', 'D', 'T')),
CONSTRAINT chk_Massachusetts CHECK (Massachusetts IN ('R', 'D', 'T')),
CONSTRAINT chk_Michigan CHECK (Michigan IN ('R', 'D', 'T')),
CONSTRAINT chk_Minnesota CHECK (Minnesota IN ('R', 'D', 'T')),
CONSTRAINT chk_Mississippi CHECK (Mississippi IN ('R', 'D', 'T')),
CONSTRAINT chk_Missouri CHECK (Missouri IN ('R', 'D', 'T')),
CONSTRAINT chk_Montana CHECK (Montana IN ('R', 'D', 'T')),
CONSTRAINT chk_Nebraska CHECK (Nebraska IN ('R', 'D', 'T')),
CONSTRAINT chk_Nevada CHECK (Nevada IN ('R', 'D', 'T')),
CONSTRAINT chk_New_Hampshire CHECK (New_Hampshire IN ('R', 'D', 'T')),
CONSTRAINT chk_New_Jersey CHECK (New_Jersey IN ('R', 'D', 'T')),
CONSTRAINT chk_New_Mexico CHECK (New_Mexico IN ('R', 'D', 'T')),
CONSTRAINT chk_New_York CHECK (New_York IN ('R', 'D', 'T')),
CONSTRAINT chk_North_Carolina CHECK (North_Carolina IN ('R', 'D', 'T')),
CONSTRAINT chk_North_Dakota CHECK (North_Dakota IN ('R', 'D', 'T')),
CONSTRAINT chk_Ohio CHECK (Ohio IN ('R', 'D', 'T')),
CONSTRAINT chk_Oklahoma CHECK (Oklahoma IN ('R', 'D', 'T')),
CONSTRAINT chk_Oregon CHECK (Oregon IN ('R', 'D', 'T')),
CONSTRAINT chk_Pennsylvania CHECK (Pennsylvania IN ('R', 'D', 'T')),
CONSTRAINT chk_Rhode_Island CHECK (Rhode_Island IN ('R', 'D', 'T')),
CONSTRAINT chk_South_Carolina CHECK (South_Carolina IN ('R', 'D', 'T')),
CONSTRAINT chk_South_Dakota CHECK (South_Dakota IN ('R', 'D', 'T')),
CONSTRAINT chk_Tennessee CHECK (Tennessee IN ('R', 'D', 'T')),
CONSTRAINT chk_Texas CHECK (Texas IN ('R', 'D', 'T')),
CONSTRAINT chk_Utah CHECK (Utah IN ('R', 'D', 'T')),
CONSTRAINT chk_Vermont CHECK (Vermont IN ('R', 'D', 'T')),
CONSTRAINT chk_Virginia CHECK (Virginia IN ('R', 'D', 'T')),
CONSTRAINT chk_Washington CHECK (Washington IN ('R', 'D', 'T')),
CONSTRAINT chk_West_Virginia CHECK (West_Virginia IN ('R', 'D', 'T')),
CONSTRAINT chk_Wisconsin CHECK (Wisconsin IN ('R', 'D', 'T')),
CONSTRAINT chk_Wyoming CHECK (Wyoming IN ('R', 'D', 'T')),
CONSTRAINT States_PK PRIMARY KEY (StateTableID));

SELECT * FROM STATES_T;