CREATE TABLE IF NOT EXISTS Users_T
	(UserID 		INT(8)		NOT NULL AUTO_INCREMENT,
	Username		VARCHAR(32)	NOT NULL,
	Password		VARCHAR(64)	NOT NULL,
	StateTableID	INT(8)		NOT NULL,
	CONSTRAINT Users_PK PRIMARY KEY (UserID));
